### ISSUE TITLE
Blinds not opening with resident mode when auto close disabled

### ISSUE THREAD

**Issue by fsedarkalex** [hvorragend/ha-blueprints#115]
thanks for adding the option to not auto-close blinds when resident switches to on!
Unfortunately now the blinds are never opening, even after the resident switches to OFF.

All my other CCA blinds are working except that one with the resident sensor.

Can I do anything to help troubleshooting this? Any logging or similar?

**Comment by hvorragend** [comment]
I've had a look at the code and can't understand it directly. It would really help me here if I could get a trace of it.

**Comment by hvorragend** [comment]
How are your resident blinds closed? 
Manually or via CCA?
Could it even be that a status change is missing here?

But I really need some more information like traces or at least your config.

**Comment by fsedarkalex** [comment]
I will try to pull traces.

The blinds are closed by CCA based on brightness level in the evening.
Sometimes I am opening the blinds manually and closing them again manually but ai don't think this matters.

In both cases the blinds are completely closed.

I am using Home pilot for this specific blind which features bidirectional communication (HA actually knows the state)

**Comment by fsedarkalex** [comment]
Wasn't able to pull traces yet but I think I know the odds:

At the time where the presence sensor goes off, the current CCA target state should be shading and not opened.

Now the CCA is configured to prevent shading to go to a higher state.

Wouldn't this also cancel out opening after resident switches to off in this case?

Will a present resident still cause shading to not occur if I disable the prevent option?

**Comment by fsedarkalex** [comment]
I wanted to check the traces today but my zigbee coordinater failed yesterday and I did not notice so I got no recent traces...

Will check again tomorrow

But meanwhile here is my config:
```
alias: "CCA: Schlafzimmer"
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    shading_forecast_sensor: weather.forecast_home
    auto_options:
      - auto_down_enabled
      - auto_sun_enabled
      - auto_shading_enabled
      - auto_brightness_enabled
      - auto_ventilate_enabled
      - auto_up_enabled
    blind: cover.rolloschlafen
    time_control: time_control_schedule
    time_up_early: "07:00:00"
    time_up_late: "08:30:00"
    time_up_late_non_workday: "08:30:00"
    close_tilt_position: 5
    time_down_early: "17:00:00"
    time_down_early_non_workday: "17:00:00"
    time_down_late: "21:00:00"
    time_down_late_non_workday: "21:00:00"
    default_brightness_sensor: sensor.einfahrt_bewegungsmelderhaustuer_illuminance_lux
    brightness_time_duration: 300
    brightness_up: 200
    brightness_down: 100
    position_tolerance: 1
    shading_position: 30
    shading_tilt_position: 75
    shading_min_temperatur1: 18
    shading_temperatur_sensor1: sensor.aussenthermometer_temperatur
    shading_forecast_temp: 20
    shading_weather_conditions:
      - sunny
      - partlycloudy
      - clear
    ignore_after_manual_config: []
    individual_config:
      - prevent_shading_end_if_closed
      - allow_shading_multiple_times
      - prevent_closing_by_resident
    time_schedule_helper: schedule.shutter_automation_schedule_helper
    ventilate_position: 25
    ventilate_tilt_position: 80
    shading_min_temperatur2: 21
    auto_shading_start_condition:
      - condition: state
        entity_id: input_boolean.summer_mode
        state: "on"
    check_config: false
    sun_time_duration: 60
    sun_elevation_up: 0
    sun_elevation_down: 0
    shading_azimuth_start: 80
    shading_azimuth_end: 160
    shading_elevation_min: 20
    shading_elevation_max: 65
    shading_waitingtime_end: 600
    contact_sensor: binary_sensor.schlafen_fenster_contact
    auto_ventilate_options: []
    close_position: 0
    cover_status_helper: input_text.cca_state_helper_for_schlafen_fenster
    drive_time: 60
    cover_status_options: cover_helper_enabled
    resident_sensor: binary_sensor.schlafen_presence_presence
```
