### ISSUE TITLE
Vetilation trigger always opens the roller shutter

### ISSUE THREAD

**Issue by EckeFL** [hvorragend/ha-blueprints#153]
The set “Ventilation position” has no effect. The roller shutter is always opened completely.

The roller shutter is not closed after the window is closed. 
To test this, I moved the roller shutter below the “Ventilation position” with the window open. When I then closed the window, the roller shutter was opened again.

```
alias: Rollladen Automation Schlafzimmer
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rollladen_schlafzimmer
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
      - auto_sun_enabled
      - auto_ventilate_enabled
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.schlafzimmer_roll_level_helper
    drive_time: 22
    ventilate_position: 73
    workday_sensor: binary_sensor.workday_sensor
    time_up_early_non_workday: "09:00:00"
    time_up_late_non_workday: "10:00:00"
    time_up_late: "07:00:00"
    default_brightness_sensor: sensor.helligkeit
    brightness_up: 100
    brightness_down: 130
    contact_window_opened: binary_sensor.fenster_schlafzimmer_beide
    check_config: true
```
