### ISSUE TITLE
distinction between CCA and manual actions

### ISSUE THREAD

**Issue by DOliana** [hvorragend/ha-blueprints#156]
Hi. I have an issue where shading is not working. By looking at the logs of the CCA helper it seems, that the automated opening in the morning is recognized as a manual operation which then prevents shading some hours later. 

What happened:
- no manual change
- at 7:22 the covers were opened (correctly)
- at 9:23 the covers should have gone into shading mode but didn't

Below is an example of the helper changes for today. I see the time in the "manual" entry changes even though there was no manual control of the cover.

config:
```
alias: Cover Control Automation - Büro
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.buero_rolladen
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
      - auto_shading_enabled
    workday_sensor: binary_sensor.workday_sensor
    time_up_early: "07:00:00"
    time_up_late: "08:00:00"
    time_down_early: "19:00:00"
    time_down_late: "22:00:00"
    time_up_early_non_workday: "07:30:00"
    time_up_late_non_workday: "08:00:00"
    time_down_early_non_workday: "19:00:00"
    time_down_late_non_workday: "22:00:00"
    check_config: false
    sun_elevation_down: -5
    sun_elevation_up: -2
    drive_delay_random: 0
    check_config_debuglevel: info
    cover_status_helper: input_text.cover_helper_buero
    cover_status_options: cover_helper_enabled
    shading_elevation_max: 60
    shading_elevation_min: 11
    shading_azimuth_end: 205
    shading_weather_conditions:
      - sunny
      - clear
      - partlycloudy
    shading_forecast_sensor: weather.forecast_home
    shading_position: 55
    position_tolerance: 3
    shading_azimuth_start: 103
    individual_config:
      - prevent_opening_multiple_times
      - prevent_shading_multiple_times
    ignore_after_manual_config: []
    reset_override_config: reset_timeout
    reset_override_time: "03:00:00"
    reset_override_timeout: 120
    auto_shading_start_condition: []
    shading_forecast_temp: 0
    shading_waitingtime_start: 0
    shading_waitingtime_end: 0
    sun_time_duration: 0
    auto_shading_end_condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "off"
```

CCA helper changes:
![image](https://github.com/user-attachments/assets/8dd0cc82-8d80-4440-b1f9-81fc64a8bf2d)
