### ISSUE TITLE
Opening on Sun elevation not working with external Schedule Helper (Bug)

### ISSUE THREAD

**Issue by DerBundesadler** [hvorragend/ha-blueprints#173]
I was struggeling with my blindes to open on Sun Elevation (in winter time after the normal opening time).

What i found out that it is not working when I use an external schedule helper as an indicator for the opening time.
I made it work, when I changed the automation to use the blueprint input variables.

This is the configuration of a blind that is **not** working:

```
alias: Rollo EG Küche
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rollo_kueche
    cover_status_helper: input_text.rollo_status_kueche
    drive_time: 60
    cover_status_options: cover_helper_enabled
    time_control: time_control_schedule
    time_schedule_helper: schedule.rolladen_eg
    default_sun_sensor: sun.sun
    sun_elevation_up: 3
    sun_elevation_down: 3
    check_config: true
    auto_options:
      - auto_sun_enabled
      - auto_up_enabled
      - auto_down_enabled
    auto_up_force: input_boolean.force_eg_fenster_kueche
    position_tolerance: 1
    sun_time_duration: 0
    reset_override_config: reset_timeout
    reset_override_time: "03:30:00"
    reset_override_timeout: 5
```

And this is a configuration that started to work, after I switched to blueprint input variables:

```
alias: Rollo EG Fenster
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.rollo_wz_fenster
    cover_status_options: cover_helper_enabled
    drive_time: 60
    time_control: time_control_input
    sun_elevation_up: 3
    sun_elevation_down: 3
    check_config: true
    individual_config: []
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
    position_tolerance: 1
    cover_status_helper: input_text.rollo_status_eg_fenster
    reset_override_config: reset_time
    sun_time_duration: 30
    reset_override_timeout: 5
    time_up_early: "07:00:00"
    time_up_late: "09:00:00"
    time_up_late_non_workday: "09:00:00"
    reset_override_time: "03:30:00"
```

I noticed, that there a many failed attempts to open the blind after the sun elevation event (Unfortunately I cannot include it, as the other traces have moved it out of the history)

[trace automation.rollo_eg_kuche 2025-01-31T07_32_00.351262+00_00.json](https://github.com/user-attachments/files/18614739/trace.automation.rollo_eg_kuche.2025-01-31T07_32_00.351262%2B00_00.json)
