### ISSUE TITLE
Nach automatischem Öffnen am Morgen fährt Rolladen komplett hoch

### ISSUE THREAD

**Issue by DomeGr694** [hvorragend/ha-blueprints#198]
Hallo,

ich habe den Blueprint seit dem Herbst am laufen und sehr zufrieden. Nun da es so langsam an die warme Jahreszeit geht wollte ich die Sun Shading Funktion zum laufen bekommen. Allerdings bekomm ich diese nicht zum laufen. Der Rolladen (Ost Seite) fährt morgens komplett hoch anstatt nur auf die SunShading Position zu fahren. Bitte um Hilfe. :)

Anbei die YAML

```
alias: Sofafenster
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.shellyplus2pm_d4d4dae928a4
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
      - auto_shading_enabled
    individual_config:
      - prevent_higher_position_closing
      - prevent_closing_multiple_times
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.helper_sofafenster
    time_up_early: "08:00:00"
    time_up_early_non_workday: "08:45:00"
    time_up_late: "08:30:00"
    time_up_late_non_workday: "09:30:00"
    workday_sensor: binary_sensor.workday_today
    workday_sensor_tomorrow: binary_sensor.workday_tomorrow
    lockout_tilted_options: []
    sun_elevation_up: 2
    sun_elevation_down: 0
    close_position: 20
    shading_position: 30
    shading_weather_conditions:
      - sunny
      - partlycloudy
    shading_azimuth_start: 70
    shading_azimuth_end: 150
    shading_elevation_max: 90
    shading_temperatur_sensor1: sensor.wohnzimmer_temperatur
    shading_min_temperatur1: 19
    shading_forecast_sensor: weather.forecast_home
    check_config: true
    auto_down_condition: []
    sun_time_duration: 10
    time_down_late: "21:00:00"
    shading_forecast_type: hourly
    shading_forecast_temp: 10
    shading_elevation_min: 15
    reset_override_timeout: 60
    shading_waitingtime_start: 60
    shading_waitingtime_end: 60

```

**Comment by hvorragend** [comment]
Ich benötige dafür den Trace zum dazugehörigen Trigger. Nur anhand der Config kann ich das nicht erkennen.

Wenn das Rollo morgens auf 100% öffnet, dann ist das sicherlich die ganz normale Tagesöffnung. 
Vermutlich hat nie ein Shading stattgefunden bzw. wurde zuvor noch nicht erkannt.

Also braucht ich die Traces zu den Triggern "t_shading_start_pending_x" und "t_shading_start_execution".

Erfahrungsgemäß liegt das ganz oft an der Wettervorhersage. Darauf habe ich nur wenig Einfluss. Die muss nämlich nicht immer stimmen und daher führt CCA auch nichts aus.

**Comment by michi2005** [comment]
Lieber hvorragend-
erstmal danke für diesen umglaublich umfangreichen und tollen Blueprint.

Ich habe ein ähnliches Problem und daher ein Verständnisproblem.
Beschäftige mich seit 2 Tagen mit dem Sonnenschutz- heute regnet es und der Rolladen fährt nicht in den Sonnenschutz.

![Image](https://github.com/user-attachments/assets/b534acb6-b83a-4a2e-8d2e-06778280f708)

Wird mit dieser Einstellung wie auf dem Bild das Wetter berücksichtigt, obwohl ich keine Forecast Entität gesetzt habe?
Was müsste ich einstellen, damit er das Wetter gar nicht berücksichtigt?

Dankeschön im Voraus.

**Comment by hvorragend** [comment]
Gestern gab es ein Bugfix bzgl. einer bestimmten Shading-Situation. 

Und ja: Wenn die Wetter-Entität nicht angegeben wird, so wird die Wettervorhersage auch nicht verwendet.

**Comment by DomeGr694** [comment]
Kann es auch daran liegen dass mein Wetter forecast gar kein Attribut mehr für die Vorhersage hat ??

**Comment by hvorragend** [comment]
Nee. Die Attribute gibt es nicht mehr. Wurde vor langer Zeit im Core umgestellt. Siehe: https://www.home-assistant.io/integrations/weather/

Du kannst dir die Ausgabe in der Entwicklerkonsole ja mal anschauen:

```
action: weather.get_forecasts
target:
  entity_id:
    - weather.tomorrow_io_home_nowcast
data:
  type: daily 
response_variable: weather_forecast
```
