### ISSUE TITLE
shading_waitingtime_end doesn't seem to work correctly anymore

### ISSUE THREAD

**Issue by bin101** [hvorragend/ha-blueprints#206]
Last summer it worked as intended but this year after upgrading to the latest version (currently Version: 2025.05.07) I am struggling with the shading behaviour.

My assumption is that with my current config shading should start if all conditions are valid for at least 5 minutes (300s default value) and should end if any condition is not valid for at least 30 minutes (1800s custom value as in yaml). But just this afternoon I noticed the vertical roller going up and down in an guessed 5 minute interval...

<details>

<summary>yaml config</summary>

```yaml
alias: Cover Control Automation (CCA) - Wohnzimmer rechts
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.shelly_rollo_wohnzimmer_3
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
      - auto_shading_enabled
    resident_sensor: input_boolean.gast_wohnzimmer
    drive_time: 45
    cover_status_helper: input_text.cover_wz_rechts_status_helper
    cover_status_options: cover_helper_enabled
    shading_position: 10
    individual_config: []
    time_up_early_non_workday: "09:00:00"
    time_up_late: "06:15:00"
    time_up_late_non_workday: "09:15:00"
    time_down_late: "23:00:00"
    time_down_late_non_workday: "23:00:00"
    sun_elevation_down: -6
    sun_elevation_up: -5
    shading_azimuth_start: 145
    shading_azimuth_end: 275
    shading_temperatur_sensor1: sensor.htindoor_temperature
    shading_temperatur_sensor2: sensor.htoutdoor_temperature
    shading_min_temperatur2: 23
    shading_min_temperatur1: 21
    shading_forecast_temp: 25
    shading_weather_conditions:
      - sunny
      - partlycloudy
      - clear
    time_down_early: "22:30:00"
    time_down_early_non_workday: "22:30:00"
    ignore_after_manual_config:
      - ignore_shading_after_manual
    workday_sensor: binary_sensor.workday_sensor
    workday_sensor_tomorrow: binary_sensor.workday_sensor_tomorrow
    shading_elevation_min: 15
    reset_override_config: reset_timeout
    reset_override_timeout: 120
    drive_delay_fix: 5
    drive_delay_random: 0
    check_config: true
    shading_brightness_sensor: sensor.lux_wohnzimmer_rechts
    shading_waitingtime_end: 1800
    auto_global_condition:
      - condition: state
        entity_id: input_boolean.cover_party_mode
        state: "off"
    is_shading_end_immediate_by_sun_position: true
```

</details>
