### ISSUE TITLE
Beschattung

### ISSUE THREAD

**Issue by bmause** [hvorragend/ha-blueprints#207]
Hallo,

meine Beschattungen hast das ganze letzte Jahr gut funktioniert, leider geht es mit der Aktuellen Version nicht mehr.
Leider verstehe ich nicht warum.
Was ist mit dem shading_forecast_sensor gemeint? woher kommt dieser und was sollte drin stehen?

HA Version 
CCA Version: 2025.05.11

Hier was von Trace:

Führe eine Aktion nur unter einer Bedingung aus

Ausgeführt: 12. Mai 2025 um 17:37:48
if

Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: false
if/condition/0

[Unbekannte Bedingung]
Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: true
entities: []
if/condition/1

[Unbekannte Bedingung]
Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: true
entities: []
if/condition/2

[Unbekannte Bedingung]
Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: true
entities: []
if/condition/3

[Unbekannte Bedingung]
Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: true
entities:
  - weather.pirateweather
if/condition/4

[Unbekannte Bedingung]
Ausgeführt: 12. Mai 2025 um 17:37:48
Ergebnis:
result: false
entities: []

```
if:
  - '{{ is_shading_enabled }}'
  - '{{ not prevent_forecast_service }}'
  - '{{ (shading_forecast_sensor != [] ) }}'
  - >-
    {{ states(shading_forecast_sensor) not in ['unavailable', 'unknown', 'query
    failed']  }}
  - '{{ trigger.id is defined }}'
  - '{{ trigger.id | regex_match(''^(t_shading_start|t_open_1|t_open_3)'') }}'
  - '{{ shading_forecast_sensor.startswith(''weather.'') }}'
then:
  - action: weather.get_forecasts
    target:
      entity_id: weather.pirateweather
    data:
      type: weather_attributes
    response_variable: weather_forecast
```

```
`id: '1747062151441'
alias: test Küche
description: ''
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.roll_kuche_cover_0
    auto_options:
      - auto_up_enabled
      - auto_down_enabled
      - auto_brightness_enabled
      - auto_shading_enabled
      - auto_sun_enabled
    cover_status_helper: input_text.helfer_roll_quiche
    cover_status_options: cover_helper_enabled
    time_up_early_non_workday: '07:45:00'
    time_up_late: '06:30:00'
    time_up_late_non_workday: '07:45:00'
    time_down_early: '20:15:00'
    time_down_early_non_workday: '20:55:00'
    workday_sensor: binary_sensor.ferien_erkannt
    default_brightness_sensor: sensor.gw1100a_solar_lux
    brightness_up: 5
    brightness_down: 5
    shading_brightness_sensor: sensor.gw1100a_solar_lux
    shading_sun_brightness_end: 8000
    shading_azimuth_start: 208
    shading_azimuth_end: 288
    shading_elevation_min: 12
    shading_temperatur_sensor1: sensor.wohnen_room_climate_control_temperatur
    shading_temperatur_sensor2: sensor.gw1100a_outdoor_temperature
    shading_forecast_type: hourly
    shading_waitingtime_start: 0
    shading_waitingtime_end: 300
    shading_min_temperatur2: 12
    shading_forecast_sensor: weather.pirateweather`
```
