### ISSUE TITLE
Manual Opening in the morning not well used to allow Shading before Scheduled Opening

### ISSUE THREAD

**Issue by Maker3457** [hvorragend/ha-blueprints#209]
Hi,

I have a problem where I'm not sure if its a configuration issue on my side or a logic error in the blueprint. But as I tried so many things already to fix it and getting out of ideas I guess its more a logic error. 

**My Scenario:**

    auto_options:
      - auto_shading_enabled
      - auto_down_enabled
      - auto_sun_enabled
    time_schedule_helper: schedule.cca_rolladen_zeitplan
    time_up_early_non_workday: "06:00:00"
    time_up_late: "10:00:00"
    time_up_late_non_workday: "10:00:00"

The time_schedule_helper is set to open the cover every morning at 8:00. On Top do I open the cover triggered by an weekly alarm schedule (I do not have to wake up every day the same time) on my Alexa device so that the covers open when the alarm wakes me up. Opening the cover is done by grouping all covers and set an open action for the group - from my point of view this is a manunal activity similar to pressing the button on the device and should be recongnized by CCA that the cover is now open (100%). I prefere to use the time_schedule_helper method as I have plenty shutters and whenever I want to change the schedule its better done with a single helper rather than updating many times the  time_up_late value in each CCA setup. 

With this configuration I accomplish that during weekdays, when I have an active alarm on my Alexa device the cover open after the alarm wakes me up and on weekends where no alarm is set the cover is opens latest at 8:00. So far so good. 

**The issue now:**

Sun shading does not start before 8:00 - my best guess is that CCA does not allow this as the manual open of the cover is either not detected or not used for sun protection. 

**And furthermore:**

When I manually start sun protection (either by moving the cover to the very same position as configured in CCA or by using a input_boolean to use the foce action for sun protection in CCA and release the input_boolean again with an additional action in CCA) the cover is opened 100% strict at 8:00 again to go back to sun protection after the configured delay is passed.

From my feeling is CCA not detecting the manual action for open position nor the manual or foced move to sun protect position well enough. If the cover is detected in a known position which is not the close position the open by time should do nothing and daytime should not be a condition for sun protection if the cover is manually opened to open position before the schedule.

If needed I can provide you my complete CCA configuration yaml as well traces when you let me know which event is of your interest for any debugging (In the morning between 6 and 8 there are plenty traces created for all the various triggers kicking in)

**Comment by hvorragend** [comment]
The shading is actually detected even if the roller blind is still closed. This raises the question of why the shading was not recognized. 

But I need more information for this. Your config and preferably also all traces of the morning hours. 

Another question: Is your version up to date? There have been a few fixes.

**Comment by Maker3457** [comment]
Hi,

most of the time I update the blueprint when a new version is released. Actually I'm using 2025.05.13 since this morning - unfortunately after the time period in scope. I can report tomorrow if with this version my issue has changed.  Find below my configuration. I will capture traces tomorrow morning. Actually this is not that easy as I need to be online in the critical period between 6 and 8 to prevent the traces are purged too fast. 

```
alias: CCA EG Wintergarten
description: ""
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.eg_wintergarten_jalousie
    auto_options:
      - auto_shading_enabled
      - auto_up_enabled
      - auto_down_enabled
      - auto_sun_enabled
    brightness_up: 10
    brightness_down: 100
    brightness_time_duration: 0
    shading_brightness_sensor: sensor.eg_wintergarten_tursensor_illuminance
    shading_sun_brightness_start: 180
    shading_sun_brightness_end: 30
    cover_status_helper: input_text.cca_eg_wintergarten
    drive_time: 55
    time_control: time_control_schedule
    cover_status_options: cover_helper_enabled
    shading_azimuth_end: 200
    shading_azimuth_start: 50
    shading_forecast_type: hourly
    shading_weather_conditions:
      - sunny
    shading_waitingtime_end: 600
    shading_elevation_min: 0
    sun_elevation_down: -18
    sun_time_duration: 0
    sun_elevation_up: -90
    time_schedule_helper: schedule.cca_rolladen_zeitplan
    time_up_early_non_workday: "06:00:00"
    time_up_late: "10:00:00"
    time_up_late_non_workday: "10:00:00"
    time_down_late: "23:59:00"
    time_down_late_non_workday: "23:59:00"
    auto_down_condition:
      - condition: state
        entity_id: light.eg_wintergarten_deckenspots
        state: "off"
    auto_shading_start_action:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.abdunkeln_eg_wintergarten
    individual_config: []
    auto_shading_end_action: []
    auto_up_action: []
    auto_down_action: []
    drive_delay_random: 0
    open_position: 100
    close_position: 0
    open_tilt_position: 100
    close_tilt_position: 0
    ventilate_position: 70
    ventilate_tilt_position: 60
    shading_position: 25
    shading_tilt_position: 25
    position_tolerance: 4
    shading_min_temperatur2: 10
    tilt_delay: 40
    shading_temperatur_sensor1: sensor.eg_wintergarten_tahsensor_temperature
    shading_min_temperatur1: 20.5
    cover_tilt_config: cover_tilt_enabled
    ignore_after_manual_config: []
    reset_override_timeout: 1
    auto_shading_start_force: input_boolean.abdunkeln_eg_wintergarten
    shading_tilt_position_3: 40
    shading_tilt_position_2: 30
    is_shading_end_immediate_by_sun_position: true
    reset_override_config: reset_timeout
```
