### ISSUE TITLE
Return to shading after ventilation

### ISSUE THREAD

**Issue by cybe** [hvorragend/ha-blueprints#43]
Hi!

I setup CCA to only use shading and ventilation. I trigger ventilation with a presence sensor. The thought is to open the cover temporarily during active shading to have some light in the room. The ventilation got activated as expected. But when the "Contact Sensor Entity" returned to `off`, the state of the cover remained in the ventilation position. Shouldn't the cover return to the shading position, like it was before?

Blueprint version: `2024.03.21-01`
Blueprint configuration:
```yaml
blind: cover.bad_terrasse_doppelwippschalter_rolladen
auto_options:
  - auto_shading_enabled
  - auto_ventilate_enabled
shading_position: 20
shading_brightness_sensor: sensor.gzcgq11lm_a_illuminance_lux
shading_sun_brightness_start: 30000
shading_sun_brightness_end: 25000
shading_azimuth_start: 40
shading_azimuth_end: 195
shading_elevation_min: 10
cover_status_helper: input_text.cca_bad
cover_status_options: cover_helper_enabled
contact_sensor: binary_sensor.bthome_sensor_91de_motion
ventilate_position: 75
auto_ventilate_options:
  - ventilation_if_lower_enabled
position_tolerance: 5
```

Attached are three traces: 

1. [Activate ventilation on motion detection (Contact Sensor Entity = On)](https://github.com/hvorragend/ha-blueprints/files/14720904/trace.automation.cca_bad.2024-03-22T09.05.53.775602%2B00.00.json)
2. [Some trigger for the current position](https://github.com/hvorragend/ha-blueprints/files/14720903/trace.automation.cca_bad.2024-03-22T09.07.10.035294%2B00.00.json)
3. [Trigger for Contact Sensor Entity = Off)](https://github.com/hvorragend/ha-blueprints/files/14720902/trace.automation.cca_bad.2024-03-22T09.07.24.624547%2B00.00.json)

The third trace however did not result the cover to be switched back to shading.

The state of the status helper before trace 1 was:
```
{
  "open":{
    "a":false,
    "t":0
  },
  "close":{
    "a":false,
    "t":0
  },
  "ventilate":{
    "a":false,
    "t":0
  },
  "shading":{
    "a":true,
    "t":1711097531
  },
  "locked":{
    "a":false,
    "t":0
  },
  "manual":{
    "a":false,
    "t":1711055450
  },
  "p":100,
  "v":4,
  "t":1711097531
}
```

**Comment by cybe** [comment]
This also occurs when the external cover status helper is not in use.

**Comment by cybe** [comment]
Thanks for the clarification. Would this be possible with the lockout protection? Will the blind move from a shading position to the open position when the door contact is on/true?

**Comment by hvorragend** [comment]
I don't quite understand that. Why should we check the door contact when we open it? 
It is being opened. So higher than before.

**Comment by cybe** [comment]
Sorry, I didn't meant _open_ position, I meant the _ventilate_ position. So you're right, there is no need to check the door contact when we open the cover or at shading end. So what I actually meant to ask is this:

Will the blind move from a _shading_ position to the _ventilate_ position when the door contact is _on_/_true_? And will the cover also move back from the _ventilate_ position to the _shading_ position when the door contact switches back to _off_/_false_?

But I already checked the code and this is not the case for the lockout protection. The question would be, whether a lockout protection is needed for shading. I guess so, even for shading. But I also think the complexity of conditions will explode further which complicates maintainability. I also don't need that mechanism personally ;)

**Comment by cybe** [comment]
> Ventilation is currently only possible when the roller blind is closed.

But shouldn't [`ventilation_if_lower_enabled`](https://github.com/hvorragend/ha-blueprints/blob/b0fd69ca220a01e9f3ff50330dc786df79a519f8/blueprints/automation/cover_control_automation.yaml#L2479) in `ANCHOR: CONTACT OPEN` allow exactly that?

I think the inverse is missing in `ANCHOR: CONTACT CLOSED`. The inverse should move the cover from the _ventilate_ position back to the state before the _ventilate_ position. Which could be the `close_position` but also for instance the `shading_position`.

**Comment by hvorragend** [comment]
No returning to previous state at the moment. 
But I have added the lockout protection.

**Comment by cybe** [comment]
Hi, shouldn't this be implemented by now? See: https://github.com/hvorragend/ha-blueprints/blob/759ec5766a3968823a100deea15c4d50a3af3eb4/blueprints/automation/cover_control_automation.yaml#L3386

As I understand, when "shading" in the Cover Status Helper was "true" before ventilation was activated, it should return to shading when the Contact Sensor is closed again? However, the Cover opened instead.

I attach two traces:
- Contact sensor opened which activated the ventilation (during shading): 
[trace automation.cca_dennis_rolladen_terrasse_links 2024-07-05T10_39_51.448161+00_00.json](https://github.com/user-attachments/files/16108924/trace.automation.cca_dennis_rolladen_terrasse_links.2024-07-05T10_39_51.448161%2B00_00.json)
- Contact sensor opened closed which opened the cover instead of returning to shading: 
[trace automation.cca_dennis_rolladen_terrasse_links 2024-07-05T10_40_51.299975+00_00.json](https://github.com/user-attachments/files/16108928/trace.automation.cca_dennis_rolladen_terrasse_links.2024-07-05T10_40_51.299975%2B00_00.json)

The first trace set the following in the status helper: `{"open":{"a":true,"t":1720173799},"close":{"a":false,"t":0},"ventilate":{"a":true,"t":1720175992},"shading":{"a":true,"t":1720173799},"locked":{"a":false,"t":0},"manual":{"a":false,"t":1720130460},"p":15,"v":4,"t":1720175992}`

The second trace set this to the status helper: `{"open":{"a":true,"t":1720176051},"close":{"a":false,"t":0},"ventilate":{"a":false,"t":1720175992},"shading":{"a":false,"t":1720173799},"locked":{"a":false,"t":0},"manual":{"a":false,"t":1720130460},"p":30,"v":4,"t":1720176051}`

Note the `shading a: false`.

Configuration:
```yaml
id: '1710702537353'
alias: CCA - Dennis - Terrasse Links
description: ''
use_blueprint:
  path: hvorragend/cover_control_automation.yaml
  input:
    blind: cover.dennis_terrasse_doppelwippschalter_unten_rolladen_links
    cover_status_options: cover_helper_enabled
    cover_status_helper: input_text.cca_dennis_terrasse_links
    auto_options:
      - auto_shading_enabled
      - auto_ventilate_enabled
    shading_brightness_sensor: sensor.illuminance_outside_maximum_averaged
    shading_azimuth_start: 140
    shading_azimuth_end: 285
    shading_elevation_min: 10
    shading_sun_brightness_start: 20000
    shading_sun_brightness_end: 10000
    shading_position: 15
    position_tolerance: 5
    drive_delay_random: 0
    time_control: time_control_disabled
    reset_override_config: reset_time
    ignore_after_manual_config:
      - ignore_shading_after_manual
    contact_sensor: binary_sensor.bthome_sensor_f918_motion
```
