### ISSUE TITLE
Feature Request: Mold/Frost Prevension

### ISSUE THREAD

**Issue by andreaalloway** [hvorragend/ha-blueprints#66]
I'd like to request an addition to this blueprint to integrate a mold/frost prevention feature into the integration.

Currently for home owners that live in areas of freezing temperatures when the blinds are fully down and say you own a insulating blind (Such as a honeycomb style blind). If the blind is fully down the temperature between the glass and the blind can drop below the dewpoint of the indoor air. This causes moisture to condense on windows and causes moisture for mold to form.
In extreme cases (Such as us Canadians are familiar with) the temperature can go below zero and water will freeze on the inside of the window.
I would propose adding a feature to this blueprint to allow binds to automatically be raised a small bit using the Mold Indicator integration. https://www.home-assistant.io/integrations/mold_indicator/ 
This helps circulate air between the glass and the window to prevent the dewpoint from being reached on the glass surface.

An example blueprint I have been using is this and it would be great to have a similar feature included in this blueprint.

```
blueprint:
  name: Cold Blinds
  description: "# Cold Blinds \n\nOpens the blinds when it is excessively cold out\n"
  domain: automation
  input:
    cover_target:
      name: Blind
      description: "The Blind or Window Cover that should be controlled by the automation"
      selector:
        entity:
          domain: cover
    sensor_target:
      name: Mold Sensor
      description: "The Mold Sensor for determining the if the dew point is going to be reached at the window\nhttps://www.home-assistant.io/integrations/mold_indicator/"
      selector:
        entity:
          domain: sensor
    mold_percentage:
      name: Mold Percentage
      description: "Percentage of mold indicator. Recommended is 70%"
      default: 80
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          unit_of_measurement: percent
          mode: slider
    open_percentage:
      name: Open Percentage
      description: "Percentage of covering to open when the mold indicator indicates risk."
      default: 3
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          unit_of_measurement: percent
          mode: slider
    include_sun:
      name: Use The Sun Option (Optional)
      description: Select enable or disable.
      default: none
      selector:
        select:
          options:
          - label: Enable the sun option
            value: sun_enabled
          - label: Disable the sun option
            value: sun_disabled
          custom_value: false
          multiple: false
    sun_elevation:
      name: Sun Elevation
      description: This is the angle between the sun and the horizon. Negative values
        mean the sun is BELOW the horizon. Guide is -1.5 (dusk) and -4.0 (dawn).
      default: 4
      selector:
        number:
          min: -10.0
          max: 5.0
          step: 0.5
          unit_of_measurement: degrees
          mode: slider
mode: restart
max_exceeded: silent
variables:
  cover_target: !input cover_target
  sensor_target: !input sensor_target
  mold_percentage: !input mold_percentage
  open_percentage: !input open_percentage
  include_sun: !input include_sun
  sun_elevation: !input sun_elevation
trigger:
- platform: numeric_state
  entity_id: sun.sun
  attribute: elevation
  below: !input sun_elevation
- platform: numeric_state
  entity_id: !input sensor_target
  above: !input mold_percentage
- platform: numeric_state
  entity_id: !input cover_target
  attribute: current_position
  below: !input open_percentage
condition:
- condition: numeric_state
  entity_id: !input cover_target
  attribute: current_position
  below: !input open_percentage
- condition: or
  conditions:
  - '{{ include_sun == ''none'' }}'
  - '{{ include_sun == ''sun_disabled'' }}'
  - '{{ (include_sun == ''sun_enabled'') and (state_attr(''sun.sun'',''elevation'')
    <= sun_elevation | float(90)) }}'
- condition: numeric_state
  entity_id: !input sensor_target
  above: !input mold_percentage
action:
  service: cover.set_cover_position
  target: 
    entity_id: !input cover_target
  data:
    position: !input open_percentage
```
